### PR TITLE
Style Changes

### PR DESCRIPTION
**Pull request by Parker-CP**
I re-organized the css stylesheet,
I changed the forms to have larger text-areas, smaller state input fields, and to be aligned with their respective titles,
Added a background image to the website and updated boxes/text accordingly
added styling to the user-search bar

ALL TESTS PASSING

### CODE REVIEW

**Comment by icorson3** [comment]
Before I merge this, can you delete the DS Store and re commit. Thanks.

**Comment by Parker-CP** [comment]
I believe we need the DS_STORE as there is a change due to adding a background image.

**Comment by robbiejaeger** [comment]
@ExCaelum It shouldn’t be necessary for our app... DS_Store is usually created if Finder was used to change a file. If you remove it, does everything still run normally?

**Comment by Parker-CP** [comment]
Yes it does, sorry I was confused

**Pull request merged**
